---
deployment:
  tasks:
    - /bin/rm -f /home/dbryqtwn/public_html/index.php
    - /bin/rm -f /home/dbryqtwn/public_html/index.html
    - /bin/cp /home/dbryqtwn/repositories/Public/index.html /home/dbryqtwn/public_html/
